export const districtsData = [
    { id: 1, name: 'Bhojpur' },
    { id: 2, name: 'Dhankuta' },
    { id: 3, name: 'Ilam' },
    { id: 4, name: 'Jhapa' },
    { id: 5, name: 'Khotang' },
    { id: 6, name: 'Morang' },
    { id: 7, name: 'Okhaldhunga' },
    { id: 8, name: 'Panchthar' },
    { id: 9, name: 'Sankhuwasabha' },
    { id: 10, name: 'Solukhumbu' },
    { id: 11, name: 'Sunsari' },
    { id: 12, name: 'Taplejung' },
    { id: 13, name: 'Terhathum' },
    { id: 14, name: 'Udayapur' },
    { id: 15, name: 'Saptari' },
    { id: 16, name: 'Siraha' },
    { id: 17, name: 'Dhanusha' },
    { id: 18, name: 'Mahottari' },
    { id: 19, name: 'Sarlahi' },
    { id: 20, name: 'Bara' },
    { id: 21, name: 'Parsa' },
    { id: 22, name: 'Rautahat' },
    { id: 23, name: 'Sindhuli' },
    { id: 24, name: 'Ramechhap' },
    { id: 25, name: 'Dolakha' },
    { id: 26, name: 'Bhaktapur' },
    { id: 27, name: 'Dhading' },
    { id: 28, name: 'Kathmandu' },
    { id: 29, name: 'Kavrepalanchowk' },
    { id: 30, name: 'Lalitpur' },
    { id: 31, name: 'Nuwakot' },
    { id: 32, name: 'Rasuwa' },
    { id: 33, name: 'Sindhupalchok' },
    { id: 34, name: 'Chitwan' },
    { id: 35, name: 'Makwanpur' },
    { id: 36, name: 'Baglung' },
    { id: 37, name: 'Gorkha' },
    { id: 38, name: 'Kaski' },
    { id: 39, name: 'Lamjung' },
    { id: 40, name: 'Manang' },
    { id: 41, name: 'Mustang' },
    { id: 42, name: 'Myagdi' },
    { id: 43, name: 'Nawalpur' },
    { id: 44, name: 'Parbat' },
    { id: 45, name: 'Syangja' },
    { id: 46, name: 'Tanahun' },
    { id: 47, name: 'Kapilvastu' },
    { id: 48, name: 'Parasi' },
    { id: 49, name: 'Rupandehi' },
    { id: 50, name: 'Arghakhanchi' },
    { id: 51, name: 'Gulmi' },
    { id: 52, name: 'Palpa' },
    { id: 53, name: 'Dang' },
    { id: 54, name: 'Pyuthan' },
    { id: 55, name: 'Rolpa' },
    { id: 56, name: 'Eastern Rukum' },
    { id: 57, name: 'Banke' },
    { id: 58, name: 'Bardiya' },
    { id: 59, name: 'Western Rukum' },
    { id: 60, name: 'Salyan' },
    { id: 61, name: 'Dolpa' },
    { id: 62, name: 'Humla' },
    { id: 63, name: 'Jumla' },
    { id: 64, name: 'Kalikot' },
    { id: 65, name: 'Mugu' },
    { id: 66, name: 'Surkhet' },
    { id: 67, name: 'Dailekh' },
    { id: 68, name: 'Jajarkot' },
    { id: 69, name: 'Kailali' },
    { id: 70, name: 'Achham' },
    { id: 71, name: 'Doti' },
    { id: 72, name: 'Bajhang' },
    { id: 73, name: 'Bajura' },
    { id: 74, name: 'Kanchanpur' },
    { id: 75, name: 'Dadeldhura' },
    { id: 76, name: 'Baitadi' },
    { id: 77, name: 'Darchula' }
];


export const localBodiesData = [
    {id: 1, name: 'Aamargadhi', districtId :75},
    {id: 2, name: 'Aathabis', districtId :67},
    {id: 3, name: 'Aathabiskot', districtId :59},
    {id: 4, name: 'Arjundhara', districtId :4},
    {id: 5, name: 'Aurahi', districtId :18},
    {id: 6, name: 'Badimalika', districtId :73},
    {id: 7, name: 'Bagchaur', districtId :60},
    {id: 8, name: 'Baglung', districtId :36},
    {id: 9, name: 'Bagmati', districtId :19},
    {id: 10, name: 'Bahudarmai', districtId :21},
    {id: 11, name: 'Balara', districtId :19},
    {id: 12, name: 'Balawa', districtId :18},
    {id: 13, name: 'Banepa', districtId :29},
    {id: 14, name: 'Bangad Kupinde', districtId :60},
    {id: 15, name: 'Banganga', districtId :47},
    {id: 16, name: 'Bansgadhi', districtId :58},
    {id: 17, name: 'Barahachhetra', districtId :11},
    {id: 18, name: 'Barahathawa', districtId :19},
    {id: 19, name: 'Barbardiya', districtId :58},
    {id: 20, name: 'Bardghat', districtId :48},
    {id: 21, name: 'Bardibas', districtId :18},
    {id: 22, name: 'Barhabise', districtId :33},
    {id: 23, name: 'Baudhimai', districtId :22},
    {id: 24, name: 'Bedkot', districtId :74},
    {id: 25, name: 'Belaka', districtId :14},
    {id: 26, name: 'Belauri', districtId :74},
    {id: 27, name: 'Belbaari', districtId :6},
    {id: 28, name: 'Belkotgadhi', districtId :31},
    {id: 29, name: 'Beni', districtId :42},
    {id: 30, name: 'Besishahar', districtId :39},
    {id: 31, name: 'Bhadrapur', districtId :4},
    {id: 32, name: 'Bhajani', districtId :69},
    {id: 33, name: 'Bhaktapur', districtId :26},
    {id: 34, name: 'Bhangaha', districtId :18},
    {id: 35, name: 'Bhanu', districtId :46},
    {id: 36, name: 'Bharatpur', districtId :34},
    {id: 37, name: 'Bheemdatta', districtId :74},
    {id: 38, name: 'Bheerkot', districtId :45},
    {id: 39, name: 'Bheri', districtId :68},
    {id: 40, name: 'Bheriganga', districtId :66},
    {id: 41, name: 'Bhimad', districtId :46},
    {id: 42, name: 'Bhimeshwar', districtId :25},
    {id: 43, name: 'Bhojpur', districtId :1},
    {id: 44, name: 'Bhumikasthan', districtId :50},
    {id: 45, name: 'Bideha', districtId :17},
    {id: 46, name: 'Bidur', districtId :31},
    {id: 47, name: 'Biratnagar', districtId :6},
    {id: 48, name: 'Birendranagar', districtId :66},
    {id: 49, name: 'Birgunj', districtId :21},
    {id: 50, name: 'Birtamod', districtId :4},
    {id: 51, name: 'Bode Barsain', districtId :15},
    {id: 52, name: 'Brindaban', districtId :22},
    {id: 53, name: 'Buddhabhumi', districtId :47},
    {id: 54, name: 'Budhanilkantha', districtId :28},
    {id: 55, name: 'Budhiganga', districtId :73},
    {id: 56, name: 'Budhinanda', districtId :73},
    {id: 57, name: 'Bungal', districtId :72},
    {id: 58, name: 'Butwal', districtId :49},
    {id: 59, name: 'Chainpur', districtId :9},
    {id: 60, name: 'Chamunda Bindrasaini', districtId :67},
    {id: 61, name: 'Chandannath', districtId :63},
    {id: 62, name: 'Chandragiri', districtId :28},
    {id: 63, name: 'Chandrapur', districtId :22},
    {id: 64, name: 'Changunarayan', districtId :26},
    {id: 65, name: 'Chapakot', districtId :45},
    {id: 66, name: 'Chaudandigadhi', districtId :14},
    {id: 67, name: 'Chaurjahari', districtId :59},
    {id: 68, name: 'Chautara Sangachowkgadhi', districtId :33},
    {id: 69, name: 'Chhayanath Rara', districtId :65},
    {id: 70, name: 'Chhedagad', districtId :68},
    {id: 71, name: 'Dakneshwari', districtId :15},
    {id: 72, name: 'Damak', districtId :4},
    {id: 73, name: 'Dasharath Chand', districtId :76},
    {id: 74, name: 'Daxinkaali', districtId :28},
    {id: 75, name: 'Deumai', districtId :3},
    {id: 76, name: 'Devchuli', districtId :43},
    {id: 77, name: 'Devdaha', districtId :49},
    {id: 78, name: 'Dewahi Gonahi', districtId :22},
    {id: 79, name: 'Dhangadhi', districtId :69},
    {id: 80, name: 'Dhangadimai', districtId :16},
    {id: 81, name: 'Dhankuta', districtId :2},
    {id: 82, name: 'Dhanushadham', districtId :17},
    {id: 83, name: 'Dharan', districtId :11},
    {id: 84, name: 'Dharmadevi', districtId :9},
    {id: 85, name: 'Dhorpatan', districtId :36},
    {id: 86, name: 'Dhulikhel', districtId :29},
    {id: 87, name: 'Dhunibeshi', districtId :27},
    {id: 88, name: 'Diktel Rupakot Majuwagadhi', districtId :5},
    {id: 89, name: 'Dipayal Silgadhi', districtId :71},
    {id: 90, name: 'Dudhauli', districtId :23},
    {id: 91, name: 'Duhabi', districtId :11},
    {id: 92, name: 'Dullu', districtId :67},
    {id: 93, name: 'Gadhimai', districtId :22},
    {id: 94, name: 'Gaindakot', districtId :43},
    {id: 95, name: 'Galkot', districtId :36},
    {id: 96, name: 'Galyang', districtId :45},
    {id: 97, name: 'Ganeshman Charnath', districtId :17},
    {id: 98, name: 'Garuda', districtId :22},
    {id: 99, name: 'Gaur', districtId :22},
    {id: 100, name: 'Gauradaha', districtId :4},
    {id: 101, name: 'Gauriganga', districtId :69},
    {id: 102, name: 'Gaushala', districtId :18},
    {id: 103, name: 'Ghodaghodi', districtId :69},
    {id: 104, name: 'Ghorahi', districtId :53},
    {id: 105, name: 'Godaita', districtId :19},
    {id: 106, name: 'Godawari', districtId :30},
    {id: 107, name: 'Godawari, Seti', districtId :69},
    {id: 108, name: 'Gokarneshwor', districtId :28},
    {id: 109, name: 'Golbazar', districtId :16},
    {id: 110, name: 'Gorkha', districtId :37},
    {id: 111, name: 'Gujara', districtId :22},
    {id: 112, name: 'Gulariya', districtId :58},
    {id: 113, name: 'Gurbhakot', districtId :66},
    {id: 114, name: 'Halesi Tuwachung', districtId :5},
    {id: 115, name: 'Hansapur', districtId :17},
    {id: 116, name: 'Hanumannagar Kankalini', districtId :15},
    {id: 117, name: 'Haripur', districtId :19},
    {id: 118, name: 'Haripurwa', districtId :19},
    {id: 119, name: 'Hariwan', districtId :19},
    {id: 120, name: 'Hetauda', districtId :35},
    {id: 121, name: 'Ilam', districtId :3},
    {id: 122, name: 'Inaruwa', districtId :11},
    {id: 123, name: 'Ishnath', districtId :22},
    {id: 124, name: 'Ishworpur', districtId :19},
    {id: 125, name: 'Itahari', districtId :11},
    {id: 126, name: 'Jaimini', districtId :36},
    {id: 127, name: 'Jaleshwar', districtId :18},
    {id: 128, name: 'Janakpur', districtId :17},
    {id: 129, name: 'Jaya Prithvi', districtId :72},
    {id: 130, name: 'Jiri', districtId :25},
    {id: 131, name: 'Jitpur Simara', districtId :20},
    {id: 132, name: 'Kabilasi', districtId :19},
    {id: 133, name: 'Kageshwori Manohara', districtId :28},
    {id: 134, name: 'Kalaiya', districtId :20},
    {id: 135, name: 'Kalika', districtId :34},
    {id: 136, name: 'Kalyanpur', districtId :16},
    {id: 137, name: 'Kamala', districtId :17},
    {id: 138, name: 'Kamalamai', districtId :23},
    {id: 139, name: 'Kamalbazar', districtId :70},
    {id: 140, name: 'Kanchanrup', districtId :15},
    {id: 141, name: 'Kankai', districtId :4},
    {id: 142, name: 'Kapilvastu', districtId :47},
    {id: 143, name: 'Karjanha', districtId :16},
    {id: 144, name: 'Katahariya', districtId :22},
    {id: 145, name: 'Katari', districtId :14},
    {id: 146, name: 'Kathmandu', districtId :28},
    {id: 147, name: 'Kawasoti', districtId :43},
    {id: 148, name: 'Khadak', districtId :15},
    {id: 149, name: 'Khairhani', districtId :34},
    {id: 150, name: 'Khandachakra', districtId :64},
    {id: 151, name: 'Khandbari', districtId :9},
    {id: 152, name: 'Kirtipur', districtId :28},
    {id: 153, name: 'Kohalpur', districtId :57},
    {id: 154, name: 'Kolhabi', districtId :20},
    {id: 155, name: 'Krishnanagar', districtId :47},
    {id: 156, name: 'Krishnapur', districtId :74},
    {id: 157, name: 'Kshireshwor Nath', districtId :17},
    {id: 158, name: 'Kushma', districtId :44},
    {id: 159, name: 'Lahan', districtId :16},
    {id: 160, name: 'Lalbandi', districtId :19},
    {id: 161, name: 'Laligurans', districtId :13},
    {id: 162, name: 'Lalitpur', districtId :30},
    {id: 163, name: 'Lamahi', districtId :53},
    {id: 164, name: 'Lamki Chuha', districtId :69},
    {id: 165, name: 'Lekbeshi', districtId :66},
    {id: 166, name: 'Letang', districtId :6},
    {id: 167, name: 'Loharpatti', districtId :18},
    {id: 168, name: 'Lumbini Sanskritik', districtId :49},
    {id: 169, name: 'Madhav Narayan', districtId :22},
    {id: 170, name: 'Madhuwan', districtId :58},
    {id: 171, name: 'Madhya Nepal', districtId :39},
    {id: 172, name: 'Madhyabindu', districtId :43},
    {id: 173, name: 'Madhyapur Thimi', districtId :26},
    {id: 174, name: 'Madi', districtId :34},
    {id: 175, name: 'Madi', districtId :9},
    {id: 176, name: 'Mahagadhimai', districtId :20},
    {id: 177, name: 'Mahakali', districtId :77},
    {id: 178, name: 'Mahakali', districtId :74},
    {id: 179, name: 'Mahalaxmi', districtId :2},
    {id: 180, name: 'Mahalaxmi', districtId :30},
    {id: 181, name: 'Maharajgunj', districtId :47},
    {id: 182, name: 'Mai', districtId :3},
    {id: 183, name: 'Malangwa', districtId :19},
    {id: 184, name: 'Manara Shisawa', districtId :18},
    {id: 185, name: 'Mandandeupur', districtId :29},
    {id: 186, name: 'Mangalsen', districtId :70},
    {id: 187, name: 'Manthali', districtId :24},
    {id: 188, name: 'Matihani', districtId :18},
    {id: 189, name: 'Maulapur', districtId :22},
    {id: 190, name: 'Mechinagar', districtId :4},
    {id: 191, name: 'Melamchi', districtId :33},
    {id: 192, name: 'Melauli', districtId :76},
    {id: 193, name: 'Mirchaiya', districtId :16},
    {id: 194, name: 'Mithila', districtId :17},
    {id: 195, name: 'Mithila Bihari', districtId :17},
    {id: 196, name: 'Musikot', districtId :51},
    {id: 197, name: 'Musikot', districtId :59},
    {id: 198, name: 'Myanglung', districtId :13},
    {id: 199, name: 'Nagarain', districtId :17},
    {id: 200, name: 'Nagarjun', districtId :28},
    {id: 201, name: 'Nalgad', districtId :68},
    {id: 202, name: 'Namobuddha', districtId :29},
    {id: 203, name: 'Narayan', districtId :67},
    {id: 204, name: 'Nepalgunj', districtId :57},
    {id: 205, name: 'Nijgadh', districtId :20},
    {id: 206, name: 'Nilkantha', districtId :27},
    {id: 207, name: 'Pachrauta', districtId :20},
    {id: 208, name: 'Pakhribas', districtId :2},
    {id: 209, name: 'Palungtar', districtId :37},
    {id: 210, name: 'Panchadewal Binayak', districtId :70},
    {id: 211, name: 'Panchapuri', districtId :66},
    {id: 212, name: 'Panchkhal', districtId :29},
    {id: 213, name: 'Panchkhapan', districtId :9},
    {id: 214, name: 'Parashuram', districtId :75},
    {id: 215, name: 'Paroha', districtId :22},
    {id: 216, name: 'Parsagadhi', districtId :21},
    {id: 217, name: 'Patan', districtId :76},
    {id: 218, name: 'Pathari Shanischare', districtId :6},
    {id: 219, name: 'Paunauti', districtId :29},
    {id: 220, name: 'Phalewas', districtId :44},
    {id: 221, name: 'Phatuwa Bijayapur', districtId :22},
    {id: 222, name: 'Phidim', districtId :8},
    {id: 223, name: 'Phungling', districtId :12},
    {id: 224, name: 'Pokhara', districtId :38},
    {id: 225, name: 'Pokhariya', districtId :21},
    {id: 226, name: 'Punarbas', districtId :74},
    {id: 227, name: 'Purchaundi', districtId :76},
    {id: 228, name: 'Putalibaazar', districtId :45},
    {id: 229, name: 'Pyuthan', districtId :54},
    {id: 230, name: 'Rainas', districtId :39},
    {id: 231, name: 'Rajapur', districtId :58},
    {id: 232, name: 'Rajbiraj', districtId :15},
    {id: 233, name: 'Rajdevi', districtId :22},
    {id: 234, name: 'Rajpur', districtId :22},
    {id: 235, name: 'Ramdhuni', districtId :11},
    {id: 236, name: 'Ramechhap', districtId :24},
    {id: 237, name: 'Ramgopalpur', districtId :18},
    {id: 238, name: 'Ramgram', districtId :48},
    {id: 239, name: 'Rampur', districtId :52},
    {id: 240, name: 'Rangeli', districtId :6},
    {id: 241, name: 'Rapti', districtId :34},
    {id: 242, name: 'Raskot', districtId :64},
    {id: 243, name: 'Ratnanagar', districtId :34},
    {id: 244, name: 'Ratuwamai', districtId :6},
    {id: 245, name: 'Resunga', districtId :51},
    {id: 246, name: 'Ropla', districtId :55},
    {id: 247, name: 'Sabaila', districtId :17},
    {id: 248, name: 'Sainamaina', districtId :49},
    {id: 249, name: 'Sandhikharka', districtId :50},
    {id: 250, name: 'Saphebagar', districtId :70},
    {id: 251, name: 'Saptakoshi', districtId :15},
    {id: 252, name: 'Shaarda', districtId :60},
    {id: 253, name: 'Shadanand', districtId :1},
    {id: 254, name: 'Shahidnagar', districtId :17},
    {id: 255, name: 'Shailyashikhar', districtId :77},
    {id: 256, name: 'Shambhunath', districtId :15},
    {id: 257, name: 'Shankharapur', districtId :28},
    {id: 258, name: 'Shikhar', districtId :71},
    {id: 259, name: 'Shiva Sataxi', districtId :4},
    {id: 260, name: 'Shivaraj', districtId :47},
    {id: 261, name: 'Shuklagandaki', districtId :46},
    {id: 262, name: 'Shuklaphanta', districtId :74},
    {id: 263, name: 'Siddharthanagar', districtId :49},
    {id: 264, name: 'Siddhicharan', districtId :7},
    {id: 265, name: 'Simraungadh', districtId :20},
    {id: 266, name: 'Siraha', districtId :16},
    {id: 267, name: 'Sitganga', districtId :50},
    {id: 268, name: 'Solu Dudhkunda', districtId :10},
    {id: 269, name: 'Sukhipur', districtId :16},
    {id: 270, name: 'Sunawarshi', districtId :6},
    {id: 271, name: 'Sundar Haraincha', districtId :6},
    {id: 272, name: 'Sundarbazar', districtId :39},
    {id: 273, name: 'Sunwal', districtId :48},
    {id: 274, name: 'Surunga', districtId :15},
    {id: 275, name: 'Suryabinayak', districtId :26},
    {id: 276, name: 'Suryodaya', districtId :3},
    {id: 277, name: 'Swargadwari', districtId :54},
    {id: 278, name: 'Tansen', districtId :52},
    {id: 279, name: 'Tarakeshor', districtId :28},
    {id: 280, name: 'Thaha', districtId :35},
    {id: 281, name: 'Thakurbaba', districtId :58},
    {id: 282, name: 'Thuli Bheri', districtId :61},
    {id: 283, name: 'Tikapur', districtId :69},
    {id: 284, name: 'Tilagufa', districtId :64},
    {id: 285, name: 'Tilottama', districtId :49},
    {id: 286, name: 'Tokha', districtId :28},
    {id: 287, name: 'Tribeni', districtId :73},
    {id: 288, name: 'Tripura Sundari', districtId :61},
    {id: 289, name: 'Triyuga', districtId :14},
    {id: 290, name: 'Tulsipur', districtId :53},
    {id: 291, name: 'Urlabari', districtId :6},
    {id: 292, name: 'Vyas', districtId :46},
    {id: 293, name: 'Waling', districtId :45},
    {id: 294, name: 'Hatuwagadhi', districtId :1},
    {id: 295, name: 'Ramprasad Rai', districtId :1},
    {id: 296, name: 'Aamchok', districtId :1},
    {id: 297, name: 'Tyamke Maiyunm', districtId :1},
    {id: 298, name: 'Arun', districtId :1},
    {id: 299, name: 'Pauwadungma', districtId :1},
    {id: 300, name: 'Salpasilichho', districtId :1},
    {id: 301, name: 'Sangurigadhi', districtId :2},
    {id: 302, name: 'Chaubise', districtId :2},
    {id: 303, name: 'Khalsa Chhintang Sahidbhumi', districtId :2},
    {id: 304, name: 'Chhathar Jorpati', districtId :2},
    {id: 305, name: 'Phakphokthum', districtId :3},
    {id: 306, name: 'Mai Jogmai', districtId :3},
    {id: 307, name: 'Chulachuli', districtId :3},
    {id: 308, name: 'Rong', districtId :3},
    {id: 309, name: 'Mangsebung', districtId :3},
    {id: 310, name: 'Sandakpur', districtId :3},
    {id: 311, name: 'Kamal', districtId :4},
    {id: 312, name: 'Buddha Shanti', districtId :4},
    {id: 313, name: 'Kachankawal', districtId :4},
    {id: 314, name: 'Jhapa', districtId :4},
    {id: 315, name: 'Barhadashi', districtId :4},
    {id: 316, name: 'Gaurigunj', districtId :4},
    {id: 317, name: 'Haldibari', districtId :4},
    {id: 318, name: 'Khotehang', districtId :5},
    {id: 319, name: 'Diprung', districtId :5},
    {id: 320, name: 'Aiselukharka', districtId :5},
    {id: 321, name: 'Jantedhunga', districtId :5},
    {id: 322, name: 'Kepilasgadhi', districtId :5},
    {id: 323, name: 'Barahpokhari', districtId :5},
    {id: 324, name: 'Lamidanda', districtId :5},
    {id: 325, name: 'Sakela', districtId :5},
    {id: 326, name: 'Jahada', districtId :6},
    {id: 327, name: 'Budi Ganga', districtId :6},
    {id: 328, name: 'Katahari', districtId :6},
    {id: 329, name: 'Dhanpalthan', districtId :6},
    {id: 330, name: 'Kanepokhari', districtId :6},
    {id: 331, name: 'Gramthan', districtId :6},
    {id: 332, name: 'Kerabari', districtId :6},
    {id: 333, name: 'Miklajung', districtId :6},
    {id: 334, name: 'Manebhanjyang', districtId :7},
    {id: 335, name: 'Champadevi', districtId :7},
    {id: 336, name: 'Sunkoshi', districtId :7},
    {id: 337, name: 'Molung', districtId :7},
    {id: 338, name: 'Chisankhugadhi', districtId :7},
    {id: 339, name: 'Khiji Demba', districtId :7},
    {id: 340, name: 'Likhu', districtId :7},
    {id: 341, name: 'Miklajung', districtId :8},
    {id: 342, name: 'Phalgunanda', districtId :8},
    {id: 343, name: 'Hilihang', districtId :8},
    {id: 344, name: 'Phalelung', districtId :8},
    {id: 345, name: 'Yangwarak', districtId :8},
    {id: 346, name: 'Kummayak', districtId :8},
    {id: 347, name: 'Tumbewa', districtId :8},
    {id: 348, name: 'Makalu', districtId :9},
    {id: 349, name: 'Silichong', districtId :9},
    {id: 350, name: 'Sabhapokhari', districtId :9},
    {id: 351, name: 'Chichila', districtId :9},
    {id: 352, name: 'Bhot Khola', districtId :9},
    {id: 353, name: 'Dudhakaushika', districtId :10},
    {id: 354, name: 'Necha Salyan', districtId :10},
    {id: 355, name: 'Dudhkoshi', districtId :10},
    {id: 356, name: 'Maha Kulung', districtId :10},
    {id: 357, name: 'Sotang', districtId :10},
    {id: 358, name: 'Khumbu Pasang Lhamu', districtId :10},
    {id: 359, name: 'Likhu Pike', districtId :10},
    {id: 360, name: 'Koshi', districtId :11},
    {id: 361, name: 'Harinagara', districtId :11},
    {id: 362, name: 'Bhokraha', districtId :11},
    {id: 363, name: 'Dewangunj', districtId :11},
    {id: 364, name: 'Gadhi', districtId :11},
    {id: 365, name: 'Barju', districtId :11},
    {id: 366, name: 'Sirijangha', districtId :12},
    {id: 367, name: 'Aathrai Triveni', districtId :12},
    {id: 368, name: 'Pathibhara Yangwarak', districtId :12},
    {id: 369, name: 'Meringden', districtId :12},
    {id: 370, name: 'Sidingwa', districtId :12},
    {id: 371, name: 'Phaktanglung', districtId :12},
    {id: 372, name: 'Maiwa Khola', districtId :12},
    {id: 373, name: 'Mikwa Khola', districtId :12},
    {id: 374, name: 'Aathrai', districtId :13},
    {id: 375, name: 'Phedap', districtId :13},
    {id: 376, name: 'Chhathar', districtId :13},
    {id: 377, name: 'Menchayayem', districtId :13},
    {id: 378, name: 'Udayapurgadhi', districtId :14},
    {id: 379, name: 'Rautamai', districtId :14},
    {id: 380, name: 'Tapli', districtId :14},
    {id: 381, name: 'Limchungbung', districtId :14},
    {id: 382, name: 'Subarna', districtId :20},
    {id: 383, name: 'Adarsha Kotwal', districtId :20},
    {id: 384, name: 'Baragadhi', districtId :20},
    {id: 385, name: 'Pheta', districtId :20},
    {id: 386, name: 'Karaiyamai', districtId :20},
    {id: 387, name: 'Prasauni', districtId :20},
    {id: 388, name: 'Bishrampur', districtId :20},
    {id: 389, name: 'Devtal', districtId :20},
    {id: 390, name: 'Parawanipur', districtId :20},
    {id: 391, name: 'Laksminiya', districtId :17},
    {id: 392, name: 'Mukhiyapatti Musaharmiya', districtId :17},
    {id: 393, name: 'Janak Nandini', districtId :17},
    {id: 394, name: 'Aaurahi', districtId :17},
    {id: 395, name: 'Bateshwar', districtId :17},
    {id: 396, name: 'Dhanauji', districtId :17},
    {id: 397, name: 'Sonama', districtId :18},
    {id: 398, name: 'Pipara', districtId :18},
    {id: 399, name: 'Samsi', districtId :18},
    {id: 400, name: 'Ekdara', districtId :18},
    {id: 401, name: 'Mahottari Rural Municipality', districtId :18},
    {id: 402, name: 'Sakhuwa Prasauni', districtId :21},
    {id: 403, name: 'Jagarnathpur', districtId :21},
    {id: 404, name: 'Chhipaharmai', districtId :21},
    {id: 405, name: 'Bindabasini', districtId :21},
    {id: 406, name: 'Paterwa Sugauli', districtId :21},
    {id: 407, name: 'Jeera Bhavani', districtId :21},
    {id: 408, name: 'Kalikamai', districtId :21},
    {id: 409, name: 'Pakaha Mainpur', districtId :21},
    {id: 410, name: 'Thori', districtId :21},
    {id: 411, name: 'Dhobini', districtId :21},
    {id: 412, name: 'Durga Bhagawati', districtId :22},
    {id: 413, name: 'Yamunamai', districtId :22},
    {id: 414, name: 'Tilathi Koiladi', districtId :15},
    {id: 415, name: 'Belhi Chapena', districtId :15},
    {id: 416, name: 'Chhinnamasta', districtId :15},
    {id: 417, name: 'Mahadeva', districtId :15},
    {id: 418, name: 'Aagnisaira Krishnasawaran', districtId :15},
    {id: 419, name: 'Rupani', districtId :15},
    {id: 420, name: 'Balan-Bihul', districtId :15},
    {id: 421, name: 'Bishnupur', districtId :15},
    {id: 422, name: 'Tirhut', districtId :15},
    {id: 423, name: 'Chandranagar', districtId :19},
    {id: 424, name: 'Bramhapuri', districtId :19},
    {id: 425, name: 'Ramnagar', districtId :19},
    {id: 426, name: 'Chakraghatta', districtId :19},
    {id: 427, name: 'Kaudena', districtId :19},
    {id: 428, name: 'Dhankaul', districtId :19},
    {id: 429, name: 'Bishnu', districtId :19},
    {id: 430, name: 'Basbariya', districtId :19},
    {id: 431, name: 'Parsa', districtId :19},
    {id: 432, name: 'Laksmipur Patari', districtId :16},
    {id: 433, name: 'Bariyarpatti', districtId :16},
    {id: 434, name: 'Aaurahi', districtId :16},
    {id: 435, name: 'Arnama', districtId :16},
    {id: 436, name: 'Bhagawanpur', districtId :16},
    {id: 437, name: 'Naraha', districtId :16},
    {id: 438, name: 'Nawarajpur', districtId :16},
    {id: 439, name: 'Sakhuwanankarkatti', districtId :16},
    {id: 440, name: 'Bishnupur', districtId :16},
    {id: 441, name: 'Ichchhakamana', districtId :34},
    {id: 442, name: 'Thakre', districtId :27},
    {id: 443, name: 'Benighat Rorang', districtId :27},
    {id: 444, name: 'Galchhi', districtId :27},
    {id: 445, name: 'Gajuri', districtId :27},
    {id: 446, name: 'Jwalamukhi', districtId :27},
    {id: 447, name: 'Siddhalekh', districtId :27},
    {id: 448, name: 'Tripura Sundari', districtId :27},
    {id: 449, name: 'Gangajamuna', districtId :27},
    {id: 450, name: 'Netrawati Dabjong', districtId :27},
    {id: 451, name: 'Khaniyabas', districtId :27},
    {id: 452, name: 'Ruby Valley', districtId :27},
    {id: 453, name: 'Kalinchok', districtId :25},
    {id: 454, name: 'Melung', districtId :25},
    {id: 455, name: 'Shailung', districtId :25},
    {id: 456, name: 'Baiteshwar', districtId :25},
    {id: 457, name: 'Tamakoshi', districtId :25},
    {id: 458, name: 'Bigu', districtId :25},
    {id: 459, name: 'Gaurishankar', districtId :25},
    {id: 460, name: 'Roshi', districtId :29},
    {id: 461, name: 'Temal', districtId :29},
    {id: 462, name: 'Chaunri Deurali', districtId :29},
    {id: 463, name: 'Bhumlu', districtId :29},
    {id: 464, name: 'Mahabharat', districtId :29},
    {id: 465, name: 'Bethanchok', districtId :29},
    {id: 466, name: 'Khanikhola', districtId :29},
    {id: 467, name: 'Bagmati', districtId :30},
    {id: 468, name: 'Konjyosom', districtId :30},
    {id: 469, name: 'Mahankal', districtId :30},
    {id: 470, name: 'Bakaiya', districtId :35},
    {id: 471, name: 'Manhari', districtId :35},
    {id: 472, name: 'Bagmati', districtId :35},
    {id: 473, name: 'Raksirang', districtId :35},
    {id: 474, name: 'Makawanpurgadhi', districtId :35},
    {id: 475, name: 'Kailash', districtId :35},
    {id: 476, name: 'Bhimphedi', districtId :35},
    {id: 477, name: 'Indrasarowar', districtId :35},
    {id: 478, name: 'Kakani', districtId :31},
    {id: 479, name: 'Dupcheshwar', districtId :31},
    {id: 480, name: 'Shivapuri', districtId :31},
    {id: 481, name: 'Tadi', districtId :31},
    {id: 482, name: 'Likhu', districtId :31},
    {id: 483, name: 'Suryagadhi', districtId :31},
    {id: 484, name: 'Panchakanya', districtId :31},
    {id: 485, name: 'Tarkeshwar', districtId :31},
    {id: 486, name: 'Kispang', districtId :31},
    {id: 487, name: 'Myagang', districtId :31},
    {id: 488, name: 'Khandadevi', districtId :24},
    {id: 489, name: 'Likhu Tamakoshi', districtId :24},
    {id: 490, name: 'Doramba', districtId :24},
    {id: 491, name: 'Gokulganga', districtId :24},
    {id: 492, name: 'Sunapati', districtId :24},
    {id: 493, name: 'Umakunda', districtId :24},
    {id: 494, name: 'Naukunda', districtId :32},
    {id: 495, name: 'Kalika', districtId :32},
    {id: 496, name: 'Uttargaya', districtId :32},
    {id: 497, name: 'Gosaikund', districtId :32},
    {id: 498, name: 'Aamachodingmo', districtId :32},
    {id: 499, name: 'Tinpatan', districtId :23},
    {id: 500, name: 'Marin', districtId :23},
    {id: 501, name: 'Hariharpurgadhi', districtId :23},
    {id: 502, name: 'Sunkoshi', districtId :23},
    {id: 503, name: 'Golanjor', districtId :23},
    {id: 504, name: 'Phikkal', districtId :23},
    {id: 505, name: 'Ghyanglekh', districtId :23},
    {id: 506, name: 'Indrawati', districtId :33},
    {id: 507, name: 'Panchpokhari Thangpal', districtId :33},
    {id: 508, name: 'Jugal', districtId :33},
    {id: 509, name: 'Balephi', districtId :33},
    {id: 510, name: 'Helambu', districtId :33},
    {id: 511, name: 'Bhotekoshi', districtId :33},
    {id: 512, name: 'Sunkoshi', districtId :33},
    {id: 513, name: 'Lisankhu Pakhar', districtId :33},
    {id: 514, name: 'Tripura Sundari', districtId :33},
    {id: 515, name: 'Badigad', districtId :36},
    {id: 516, name: 'Kathekhola', districtId :36},
    {id: 517, name: 'Nisikhola', districtId :36},
    {id: 518, name: 'Bareng', districtId :36},
    {id: 519, name: 'Tarakhola', districtId :36},
    {id: 520, name: 'Tamankhola', districtId :36},
    {id: 521, name: 'Shahid Lakhan', districtId :37},
    {id: 522, name: 'Barpak Sulikot', districtId :37},
    {id: 523, name: 'Aarughat', districtId :37},
    {id: 524, name: 'Siranchok', districtId :37},
    {id: 525, name: 'Gandaki', districtId :37},
    {id: 526, name: 'Bhimsen Thapa', districtId :37},
    {id: 527, name: 'Ajirkot', districtId :37},
    {id: 528, name: 'Dharche', districtId :37},
    {id: 529, name: 'Chum Nubri', districtId :37},
    {id: 530, name: 'Annapurna', districtId :38},
    {id: 531, name: 'Machhapuchhre', districtId :38},
    {id: 532, name: 'Madi', districtId :38},
    {id: 533, name: 'Rupa', districtId :38},
    {id: 534, name: 'Marsyangdi', districtId :39},
    {id: 535, name: 'Dordi', districtId :39},
    {id: 536, name: 'Dudhpokhari', districtId :39},
    {id: 537, name: 'Kwaholasothar', districtId :39},
    {id: 538, name: 'Manang Disyang', districtId :40},
    {id: 539, name: 'Nason', districtId :40},
    {id: 540, name: 'Chame', districtId :40},
    {id: 541, name: 'Narpa Bhumi', districtId :40},
    {id: 542, name: 'Gharpajhong', districtId :41},
    {id: 543, name: 'Thasang', districtId :41},
    {id: 544, name: 'Baragung Muktichhetra', districtId :41},
    {id: 545, name: 'Lomanthang', districtId :41},
    {id: 546, name: 'Lo-Thekar Damodarkunda', districtId :41},
    {id: 547, name: 'Malika', districtId :42},
    {id: 548, name: 'Mangala', districtId :42},
    {id: 549, name: 'Raghuganga', districtId :42},
    {id: 550, name: 'Dhaulagiri', districtId :42},
    {id: 551, name: 'Annapurna', districtId :42},
    {id: 552, name: 'Hupsekot', districtId :43},
    {id: 553, name: 'Binayi Triveni', districtId :43},
    {id: 554, name: 'Bulingtar', districtId :43},
    {id: 555, name: 'Baudikali', districtId :43},
    {id: 556, name: 'Jaljala', districtId :44},
    {id: 557, name: 'Modi', districtId :44},
    {id: 558, name: 'Painyu', districtId :44},
    {id: 559, name: 'Bihadi', districtId :44},
    {id: 560, name: 'Mahashila', districtId :44},
    {id: 561, name: 'Kaligandaki', districtId :45},
    {id: 562, name: 'Biruwa', districtId :45},
    {id: 563, name: 'Harinas', districtId :45},
    {id: 564, name: 'Aandhikhola', districtId :45},
    {id: 565, name: 'Arjun Chaupari', districtId :45},
    {id: 566, name: 'Phedikhola', districtId :45},
    {id: 567, name: 'Rishing', districtId :46},
    {id: 568, name: 'Myagde', districtId :46},
    {id: 569, name: 'Aanbu Khaireni', districtId :46},
    {id: 570, name: 'Bandipur', districtId :46},
    {id: 571, name: 'Ghiring', districtId :46},
    {id: 572, name: 'Devghat', districtId :46},
    {id: 573, name: 'Malarani', districtId :50},
    {id: 574, name: 'Pandini', districtId :50},
    {id: 575, name: 'Chhatradev', districtId :50},
    {id: 576, name: 'Raptisonari', districtId :57},
    {id: 577, name: 'Baijnath', districtId :57},
    {id: 578, name: 'Khajura', districtId :57},
    {id: 579, name: 'Janaki', districtId :57},
    {id: 580, name: 'Duduwa', districtId :57},
    {id: 581, name: 'Narainapur', districtId :57},
    {id: 582, name: 'Badhaiyatal', districtId :58},
    {id: 583, name: 'Geruwa', districtId :58},
    {id: 584, name: 'Rapti', districtId :53},
    {id: 585, name: 'Gadhawa', districtId :53},
    {id: 586, name: 'Babai', districtId :53},
    {id: 587, name: 'Shantinagar', districtId :53},
    {id: 588, name: 'Rajpur', districtId :53},
    {id: 589, name: 'Banglachuli', districtId :53},
    {id: 590, name: 'Dangisharan', districtId :53},
    {id: 591, name: 'Satyawati', districtId :51},
    {id: 592, name: 'Dhurkot', districtId :51},
    {id: 593, name: 'Gulmi Durbar', districtId :51},
    {id: 594, name: 'Madane', districtId :51},
    {id: 595, name: 'Chandrakot', districtId :51},
    {id: 596, name: 'Malika', districtId :51},
    {id: 597, name: 'Chhatrakot', districtId :51},
    {id: 598, name: 'Isma', districtId :51},
    {id: 599, name: 'Kaligandaki', districtId :51},
    {id: 600, name: 'Ruru', districtId :51},
    {id: 601, name: 'Mayadevi', districtId :47},
    {id: 602, name: 'Shuddhodhan', districtId :47},
    {id: 603, name: 'Yasodhara', districtId :47},
    {id: 604, name: 'Bijaynagar', districtId :47},
    {id: 605, name: 'Triveni Susta', districtId :48},
    {id: 606, name: 'Pratappur', districtId :48},
    {id: 607, name: 'Sarawal', districtId :48},
    {id: 608, name: 'Palhi Nandan', districtId :48},
    {id: 609, name: 'Rainadevi Chhahara', districtId :52},
    {id: 610, name: 'Mathagadhi', districtId :52},
    {id: 611, name: 'Nisdi', districtId :52},
    {id: 612, name: 'Bagnaskali', districtId :52},
    {id: 613, name: 'Rambha', districtId :52},
    {id: 614, name: 'Purbakhola', districtId :52},
    {id: 615, name: 'Tinau', districtId :52},
    {id: 616, name: 'Ribdikot', districtId :52},
    {id: 617, name: 'Naubahini', districtId :54},
    {id: 618, name: 'Jhimaruk', districtId :54},
    {id: 619, name: 'Gaumukhi', districtId :54},
    {id: 620, name: 'Airawati', districtId :54},
    {id: 621, name: 'Sarumarani', districtId :54},
    {id: 622, name: 'Mallarani', districtId :54},
    {id: 623, name: 'Mandavi', districtId :54},
    {id: 624, name: 'Sunil Smriti', districtId :55},
    {id: 625, name: 'Runtigadhi', districtId :55},
    {id: 626, name: 'Lungri', districtId :55},
    {id: 627, name: 'Triveni', districtId :55},
    {id: 628, name: 'Paribartan', districtId :55},
    {id: 629, name: 'Gangadev', districtId :55},
    {id: 630, name: 'Madi', districtId :55},
    {id: 631, name: 'Sunchhahari', districtId :55},
    {id: 632, name: 'Thawang', districtId :55},
    {id: 633, name: 'Bhume', districtId :56},
    {id: 634, name: 'Putha Uttarganga', districtId :56},
    {id: 635, name: 'Sisne', districtId :56},
    {id: 636, name: 'Gaidhawa', districtId :49},
    {id: 637, name: 'Mayadevi', districtId :49},
    {id: 638, name: 'Kotahimai', districtId :49},
    {id: 639, name: 'Marchawarimai', districtId :49},
    {id: 640, name: 'Siyari', districtId :49},
    {id: 641, name: 'Sammarimai', districtId :49},
    {id: 642, name: 'Rohini', districtId :49},
    {id: 643, name: 'Shuddhodhan', districtId :49},
    {id: 644, name: 'Om Satiya', districtId :49},
    {id: 645, name: 'Kanchan', districtId :49},
    {id: 646, name: 'Gurans', districtId :67},
    {id: 647, name: 'Bhairabi', districtId :67},
    {id: 648, name: 'Naumule', districtId :67},
    {id: 649, name: 'Mahabu', districtId :67},
    {id: 650, name: 'Thantikandh', districtId :67},
    {id: 651, name: 'Bhagawatimai', districtId :67},
    {id: 652, name: 'Dungeshwar', districtId :67},
    {id: 653, name: 'Mudkechula', districtId :61},
    {id: 654, name: 'Kaike', districtId :61},
    {id: 655, name: 'She Phoksundo', districtId :61},
    {id: 656, name: 'Jagadulla', districtId :61},
    {id: 657, name: 'Dolpo Buddha', districtId :61},
    {id: 658, name: 'Chharka Tangsong', districtId :61},
    {id: 659, name: 'Simkot', districtId :62},
    {id: 660, name: 'Sarkegad', districtId :62},
    {id: 661, name: 'Adanchuli', districtId :62},
    {id: 662, name: 'Kharpunath', districtId :62},
    {id: 663, name: 'Tanjakot', districtId :62},
    {id: 664, name: 'Chankheli', districtId :62},
    {id: 665, name: 'Namkha', districtId :62},
    {id: 666, name: 'Junichande', districtId :68},
    {id: 667, name: 'Kuse', districtId :68},
    {id: 668, name: 'Barekot', districtId :68},
    {id: 669, name: 'Shivalaya', districtId :68},
    {id: 670, name: 'Tatopani', districtId :63},
    {id: 671, name: 'Patarasi', districtId :63},
    {id: 672, name: 'Tila', districtId :63},
    {id: 673, name: 'Kanaka Sundari', districtId :63},
    {id: 674, name: 'Sinja', districtId :63},
    {id: 675, name: 'Hima', districtId :63},
    {id: 676, name: 'Guthichaur', districtId :63},
    {id: 677, name: 'Narharinath', districtId :64},
    {id: 678, name: 'Palata', districtId :64},
    {id: 679, name: 'Shubha Kalika', districtId :64},
    {id: 680, name: 'Sanni Triveni', districtId :64},
    {id: 681, name: 'Pachaljharana', districtId :64},
    {id: 682, name: 'Mahawai', districtId :64},
    {id: 683, name: 'Khatyad', districtId :65},
    {id: 684, name: 'Soru', districtId :65},
    {id: 685, name: 'Mugum Karmarong', districtId :65},
    {id: 686, name: 'Sani Bheri', districtId :59},
    {id: 687, name: 'Triveni', districtId :59},
    {id: 688, name: 'Banphikot', districtId :59},
    {id: 689, name: 'Kumakh', districtId :60},
    {id: 690, name: 'Kalimati', districtId :60},
    {id: 691, name: 'Chhatreshwari', districtId :60},
    {id: 692, name: 'Darma', districtId :60},
    {id: 693, name: 'Kapurkot', districtId :60},
    {id: 694, name: 'Triveni', districtId :60},
    {id: 695, name: 'Siddha Kumakh', districtId :60},
    {id: 696, name: 'Barahatal', districtId :66},
    {id: 697, name: 'Simta', districtId :66},
    {id: 698, name: 'Chaukune', districtId :66},
    {id: 699, name: 'Chingad', districtId :66},
    {id: 700, name: 'Ramaroshan', districtId :70},
    {id: 701, name: 'Chaurpati', districtId :70},
    {id: 702, name: 'Turmakhand', districtId :70},
    {id: 703, name: 'Mellekh', districtId :70},
    {id: 704, name: 'Dhankari', districtId :70},
    {id: 705, name: 'Bannigadi Jayagad', districtId :70},
    {id: 706, name: 'Dogdakedar', districtId :76},
    {id: 707, name: 'Dilashaini', districtId :76},
    {id: 708, name: 'Sigas', districtId :76},
    {id: 709, name: 'Pancheshwar', districtId :76},
    {id: 710, name: 'Surnaya', districtId :76},
    {id: 711, name: 'Shivanath', districtId :76},
    {id: 712, name: 'Kedarsyu', districtId :72},
    {id: 713, name: 'Thalara', districtId :72},
    {id: 714, name: 'Bitthadchir', districtId :72},
    {id: 715, name: 'Chhabis Pathibhera', districtId :72},
    {id: 716, name: 'Chhanna', districtId :72},
    {id: 717, name: 'Masta', districtId :72},
    {id: 718, name: 'Durgathali', districtId :72},
    {id: 719, name: 'Talkot', districtId :72},
    {id: 720, name: 'Surma', districtId :72},
    {id: 721, name: 'Saipal', districtId :72},
    {id: 722, name: 'Khaptad Chhededaha', districtId :73},
    {id: 723, name: 'Swami Kartik Khapar', districtId :73},
    {id: 724, name: 'Jagannath', districtId :73},
    {id: 725, name: 'Himali', districtId :73},
    {id: 726, name: 'Gaumul', districtId :73},
    {id: 727, name: 'Navadurga', districtId :75},
    {id: 728, name: 'Aalitaal', districtId :75},
    {id: 729, name: 'Ganyapadhura', districtId :75},
    {id: 730, name: 'Bhageshwar', districtId :75},
    {id: 731, name: 'Ajaymeru', districtId :75},
    {id: 732, name: 'Naugad', districtId :77},
    {id: 733, name: 'Malikarjun', districtId :77},
    {id: 734, name: 'Marma', districtId :77},
    {id: 735, name: 'Lekam', districtId :77},
    {id: 736, name: 'Duhu', districtId :77},
    {id: 737, name: 'Vyans', districtId :77},
    {id: 738, name: 'Api Himal', districtId :77},
    {id: 739, name: 'Aadarsha', districtId :71},
    {id: 740, name: 'Purbichauki', districtId :71},
    {id: 741, name: 'K.I. Singh', districtId :71},
    {id: 742, name: 'Jorayal', districtId :71},
    {id: 743, name: 'Sayal', districtId :71},
    {id: 744, name: 'Bogatan', districtId :71},
    {id: 745, name: 'Badikedar', districtId :71},
    {id: 746, name: 'Janaki', districtId :69},
    {id: 747, name: 'Kailari', districtId :69},
    {id: 748, name: 'Joshipur', districtId :69},
    {id: 749, name: 'Bargagoriya', districtId :69},
    {id: 750, name: 'Mohanyal', districtId :69},
    {id: 751, name: 'Chure', districtId :69},
    {id: 752, name: 'Laljhadi', districtId :74},
    {id: 753, name: 'Beldandi', districtId :74}
];